### ISSUE TITLE
Main issue tracker 📝

### ISSUE THREAD

**Issue by Hvaheterdu** [Hvaheterdu/arduino-thermo-hygrometer#32]
# Overall issue tracking for this arduino thermo hygrometer project

This is an overall issue tracker, keeping track of new features and ideas.

## Database
- [x] Complete

## Infrastructure as Code
- [ ] Set up IaC
- [ ] Set up secrets
- [ ] Set up GitHub Actions

## Testing
- [x] Unit tests
- [ ] Integration tests
- [ ] End-to-end tests

## Backend
- [ ] Add Authenitcation
- [ ] Add Authorization
- [ ] Add Redis cache

## Frontend
- [ ] Create Home-page
- [ ] Create About-page
- [ ] Create Statistics-page
